"""add_name_map_config

Revision ID: 2d34d7973dd9
Revises: 8e22df58cff8
Create Date: 2026-01-19 00:28:09.915699

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d34d7973dd9"
down_revision: str | Sequence[str] | None = "8e22df58cff8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "name_map_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=True),
        sa.Column("name_map_key", sa.String(length=255), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=True),
        sa.Column("is_global_default", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # 创建索引
    op.create_index("idx_work_id_priority", "name_map_config", ["work_id", "priority"])
    op.create_index("idx_work_id_active", "name_map_config", ["work_id", "is_active"])
    op.create_index("idx_global_default", "name_map_config", ["is_global_default"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_global_default", "name_map_config")
    op.drop_index("idx_work_id_active", "name_map_config")
    op.drop_index("idx_work_id_priority", "name_map_config")
    op.drop_table("name_map_config")
    # ### end Alembic commands ###
