"""Initial baseline migration

Revision ID: 4786d6615575
Revises:
Create Date: 2026-01-16 18:51:02.432933

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

import paihub
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4786d6615575"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pixiv",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255, collation="utf8mb4_general_ci"), nullable=True),
        sa.Column("tags", paihub.utils.sql_types.Tags(collation="utf8mb4_general_ci"), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("love_count", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("permissions", sa.Enum("OWNER", "ADMIN", "PUBLIC", name="permissionsenum"), nullable=True),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ban_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ban_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_banned", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "work",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=True),
        sa.Column("site_key", paihub.utils.sql_types.SiteKey(), nullable=True),
        sa.Column("artwork_id", sa.BigInteger(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("WAIT", "REJECT", "PASS", "MOVE", "NOT_FOUND", "ERROR", name="reviewstatus"),
            nullable=True,
        ),
        sa.Column("auto", sa.Boolean(), nullable=True),
        sa.Column("ext", paihub.utils.sql_types.JSON(), nullable=True),
        sa.Column("create_by", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_by", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_channel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("search_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_pattern", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "push",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("review_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("ext", paihub.utils.sql_types.JSON(), nullable=True),
        sa.Column("create_by", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_by", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("push")
    op.drop_table("work_rules")
    op.drop_table("work_channel")
    op.drop_table("review")
    op.drop_table("work")
    op.drop_table("users")
    op.drop_table("pixiv")
    # ### end Alembic commands ###
