"""Add AutoPushConfig table

Revision ID: 8c8daabd8fbb
Revises: 4786d6615575
Create Date: 2026-01-16 22:02:40.904809

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

import paihub

# revision identifiers, used by Alembic.
revision: str = "8c8daabd8fbb"
down_revision: Union[str, Sequence[str], None] = "4786d6615575"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_push_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("mode", sa.Enum("BATCH", "IMMEDIATE", name="autopushmode"), nullable=True),
        sa.Column("status", sa.Enum("DISABLED", "ENABLED", "RUNNING", "PAUSED", name="autopushstatus"), nullable=True),
        sa.Column("cron_expression", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("push_to_owner", sa.Integer(), nullable=True),
        sa.Column("run_once", sa.Integer(), nullable=True),
        sa.Column("ext", paihub.utils.sql_types.JSON(), nullable=True),
        sa.Column("create_by", sa.Integer(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_by", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("last_run_time", sa.DateTime(), nullable=True),
        sa.Column("next_run_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auto_push_config")
    # ### end Alembic commands ###
