"""Add run_once field to auto_push_config

Revision ID: 8e22df58cff8
Revises: 8c8daabd8fbb
Create Date: 2026-01-16 22:08:51.898883

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "8e22df58cff8"
down_revision: str | Sequence[str] | None = "8c8daabd8fbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {column["name"] for column in inspector.get_columns("auto_push_config")}

    if "run_once" not in existing_columns:
        op.add_column("auto_push_config", sa.Column("run_once", sa.Integer(), nullable=True))

    op.execute("UPDATE auto_push_config SET run_once = 0 WHERE run_once IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auto_push_config", "run_once")
    # ### end Alembic commands ###
